include:
  - board: seeeduino_xiao_ble
    shield: pling_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: pling_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset